#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    preinstall = """
        sudo yunohost tools update apps
        sudo yunohost app install https://github.com/YunoHost-Apps/zerotier_ynh --force
    """
